version: '3.8'

services:
  bot:
    build: ./bot
    container_name: telegram_bot
    env_file:
      - .env
    depends_on:
      - api

  api:
    build: ./api
    container_name: translation_api
    env_file:
      - .env
    ports:
      - "5000:5000"
