version: '3.8'

services:
  api:
    build:
      context: ./api
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5000:5000"

  bot:
    build:
      context: ./bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_URL=${API_URL}
    depends_on:
      - api
