# nixpacks.toml

[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'python38', 'pip']

[phases.install]
cmds = [
  'cd bot && yarn install',
  'cd api && pip install -r requirements.txt'
]

[start]
cmds = [
  'cd api && python app.py &',
  'cd bot && node index.js'
]